In [1]:
import numpy as np

In [7]:
my_list = [1,2,3]
my_array = np.array([1,2,3])
print(my_array)
print(type(my_list))
print(type(my_array))

[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>


#Create a numpy array from a list of list

In [11]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
arrmatrix = np.array(matrix)
arrmatrix.shape #3x3 array is returned

(3, 3)

creating arrays using built in functions

In [15]:
        #start, stop, step
print(np.arange(0,10))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


#Generate arrays of zeros or ones

In [16]:
print(np.zeros(3))
print(np.zeros((5,5)))
print(np.ones(3))
print(np.ones((3,3)))

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##Return evenly spaced numbers over a specified intervals

In [20]:
#Start, stop, number of elements

print(np.linspace(0,5,10))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [23]:
##Random number arrays

In [26]:
print(np.random.rand(2))
print(np.random.rand(5,5))

[0.44687753 0.11493021]
[[0.24046046 0.03138975 0.26601833 0.20821665 0.46379014]
 [0.78305525 0.75532934 0.05655643 0.91679697 0.93639253]
 [0.11105997 0.31926336 0.97038556 0.87863846 0.06165002]
 [0.7058919  0.14661191 0.17645171 0.95125337 0.17658372]
 [0.74404169 0.5011985  0.87482893 0.69841345 0.60258277]]


In [27]:
##From normal distrubtiions

In [29]:
#Generates a normal distribution curve (bel-curve), 'randn' signifies normal distribution
print(np.random.randn(2))
print(np.random.randn(5,5))

[ 0.50329577 -1.13854504]
[[ 1.15622784 -0.3657551  -0.44388762 -1.31526306  1.38523693]
 [-1.65147653 -1.09144586 -0.44552398  0.87498682 -0.11447028]
 [ 0.39573541 -0.50237088  0.68120126  0.59533265  2.00941736]
 [-0.31087715  0.7494255   0.01392738  0.26821132 -0.21474348]
 [ 1.00773968  1.28420024 -0.10689395 -1.1155112   0.34020711]]


In [30]:
##Random integers from low(inclusive) to high(exclusive)

In [38]:
print(np.random.randint(1,100))
print(np.random.randint(1,100,10)) #10 random numbers between 1-100 are generated

18
[ 4 47 17 67 52 79 83 66 86 55]


#Random vs Seed
...Random = Unpredictable
...Seed = Predictable

In [41]:
np.random.seed(77)
print(np.random.rand(4))

np.random.seed(77)
np.random.rand(4)

[0.91910903 0.6421956  0.75371223 0.13931457]


array([0.91910903, 0.6421956 , 0.75371223, 0.13931457])

#Change the dimensions of array

In [48]:
arr = np.arange(50) #25 elements
arr.reshape(10,5) #5x5 = 25 elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [50]:
print(arr.max()) #max value in the array
print(arr.argmax()) #maximum number of elements in the array
print(arr.min())

49
49
0


#slicing and indexing in numpy

In [54]:
arr1 = np.arange(0,11)
print(arr1)
print(f"this is the element in the 8th position: {arr[8]}")

[ 0  1  2  3  4  5  6  7  8  9 10]
this is the element in the 8th position: 8


In [57]:
arr1[1:5]=100 #setting a value with index range(broadcasting)
print(arr1)

[  0 100 100 100 100   5   6   7   8   9  10]


In [58]:
arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#Important notes on slices

In [61]:
slice = arr1[0:6]
slice

array([0, 1, 2, 3, 4, 5])

In [63]:
slice[:] = 99 #change all elements in the slice with 99
print(slice)
arr1 #elements in the original array are also changed (slice is just the reference to the original array)

[99 99 99 99 99 99]


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [65]:
arr1_copy = arr1.copy()
arr1_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
#both ways of indexing are valid
print(arr_2d[1,0])
arr_2d[1][0]

4


4

In [70]:
#2d array slicing
arr_2d[:2,1:] #row_start:row_end, col_start:col_end

array([[2, 3],
       [5, 6]])

In [71]:
#conditional selection based on the value not the index
# returns a boolean array by checking each element in the array by checking the condition provided

arr = np.arange(0,11)
print(arr>4)

[False False False False False  True  True  True  True  True  True]


In [73]:
bool_arr = arr>4
print(bool_arr)


[False False False False False  True  True  True  True  True  True]
[ 5  6  7  8  9 10]


In [ ]:
#this returns the actual values that are greater than the given condition
print(arr[bool_arr])

In [77]:
#Basic Arithmetic
arr1 = np.arange(0,11)
arr2 = np.arange(10,21)

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(1/arr1, 1/arr2)

[10 12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[  0  11  24  39  56  75  96 119 144 171 200]
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421 0.5       ]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1       ] [0.1        0.09090909 0.08333333 0.07692308 0.07142857 0.06666667
 0.0625     0.05882353 0.05555556 0.05263158 0.05      ]


C:\Users\Administrator.DAI-PC2\AppData\Local\Temp\ipykernel_20900\818148495.py:9: RuntimeWarning: divide by zero encountered in divide
  print(1/arr1, 1/arr2)


In [81]:
print(arr1**2)
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))

[  0   1   4   9  16  25  36  49  64  81 100]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]


C:\Users\Administrator.DAI-PC2\AppData\Local\Temp\ipykernel_20900\3391617673.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr1))


In [82]:
print(arr1.sum())
print(arr1.mean())
print(arr1.max())
print(arr1.min())
print(arr1.var())
print(arr1.std())

55
5.0
10
0
10.0
3.1622776601683795


In [ ]:
#2D array with 3rows and 3columns

In [84]:
print(arr_2d)
print(arr_2d.sum(axis=0), arr_2d.sum(axis=1)) #axis 0 --> sum over columns,  axis 1 --> sum over rows

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18] [ 6 15 24]


In [85]:
print(arr_2d.shape)

(3, 3)
