In [1]:
sum(range(1,3))

3

In [2]:
# initialization  different type of list 

list(range(10))
  

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
#prime number

for i in range(2,10):
    for h in range(2,i):
        if i%h==0:
            print("not prime number:",i)
            break
    else:    
        print("number is prime :",i)
            


number is prime : 2
number is prime : 3
not prime number: 4
number is prime : 5
not prime number: 6
number is prime : 7
not prime number: 8
not prime number: 9


In [4]:
i=1
while i<9:
    print(i)
    i+=1

1
2
3
4
5
6
7
8


In [14]:
n=5
def fibo(n):
    a,b=0,1
    while a<n:
        print(a,end=' ')
        a,b=b,a+b
print()
fibo(n)



0 1 1 2 3 

In [16]:
import numpy as np
print(np.zeros(3))
print(np.zeros((5,5)))
print(np.ones(3))
print(np.ones((3,3)))


[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
print(np.linspace(0,10,3))
print(np.linspace(0,10,2))
   
# print(np.linspace(0,5,20))
# print(np.linspace(0,5,21))

[ 0.  5. 10.]
[ 0. 10.]


In [21]:
np.random.randn(1,10)

array([[ 0.27249734, -0.10070775,  2.38537459, -1.17883425,  1.44042634,
        -0.17501641,  0.79989226, -0.00440444, -1.33551286,  0.05717658]])

In [ ]:
print(np.random.randn(2))
print(np.random.randn(5,5))

In [22]:
np.random.seed(77)
print(np.random.rand(4))

[0.91910903 0.6421956  0.75371223 0.13931457]


In [24]:
arr = np.arange(25) # numbers from 0 to 24
ranarr = np.random.randint(0,50,10) # 10 random numbers between 0 and 50

print(arr)
print(ranarr)

# reshape: Returns an array containing the same data with a new shape
print(arr.reshape(5,5))

# Max, Min and their index positions
print(arr.max())
print(arr.argmax())
print(arr.min())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[10  7 35  1 11 17  6 20 37 33]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
24
24
0


In [27]:
import numpy as np
import pandas as pd

# Creating a series from a Python list
myindex = ['USA','Canada','England']

mydata = [1776,1867,1821]

# Just the numeric index
myser = pd.Series(data=myindex,index=mydata)

print(myser)


1776        USA
1867     Canada
1821    England
dtype: object


In [30]:
ran_data = np.random.randint(0,100,4)
print(ran_data)

names = ['Alice','Bob','Charles','Dave']

ages = pd.Series(ran_data,names)

print(ages)

[ 4 29 51 28]
Alice       4
Bob        29
Charles    51
Dave       28
dtype: int32


es))

In [31]:
ages = {'Sammy':5,'Frank':10,'Spike':7}

print(ages)

print(pd.Series(ages))

{'Sammy': 5, 'Frank': 10, 'Spike': 7}
Sammy     5
Frank    10
Spike     7
dtype: int64
